import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ title, data }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={`${styles.header} ${inter.className}`}>
        <nav>
          <img alt="Logo" />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          {data.map((ec) => (
            <Link href={`/events/${ec.id}`} key={ec.id}>
              <Image src={ec.image} width={300} height={300} alt={ec.id} priority={true}/>
              <h2>{ec.title}</h2> <p>{ec.description}</p>
            </Link>
          ))}
        </div>
      </main>
      <footer className={styles.footer}>
        <p>© 2021 Events App</p>
      </footer>
    </div>
  );
}

// export async function getServerSideProps() {
//   console.log("getServerSideProps");
//   return {
//     props: {
//       title: "Hello everyone!",
//     },
//   };
// }
export async function getServerSideProps() {
  // const data = await import("../data.json");
  try {
    const { events_categories } = await import('/data/data.json');
    return {
      props: {
        title: 'Hello everyone!',
        data: events_categories,
      },
    };
  } catch (e) {
    console.error('error occured', e);
    return {
      props: {
        title: 'Hello everyone!',
      },
    };
  }
}
