import Head from 'next/head';
import Image from 'next/image';

import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { HomePage } from '../src/components/home/home-page';
import PropTypes from 'prop-types';
import Footer from '@/src/components/footer/Footer';
import Header from '@/src/components/header/header';


export default function Home({ title, data }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      
      {/* <main className={`${styles.main} ${inter.className}`}>
        <div>
          {data.map((ec) => (
            <Link href={`/events/${ec.id}`} key={ec.id}>
              <Image
                src={ec.image}
                width={300}
                height={300}
                alt={ec.id}
                priority={true}
              />
              <h2>{ec.title}</h2> <p>{ec.description}</p>
            </Link>
          ))}
        </div>
      </main> */}
      <HomePage data={data} />
      <Footer />
    </div>
  );
}

export async function getServerSideProps() {
  try {
    const { events_categories } = await import('/data/data.json');
    return {
      props: {
        title: 'Hello everyone!',
        data: events_categories,
      },
    };
  } catch (e) {
    console.error('error occured', e);
    return {
      props: {
        title: 'Hello everyone!',
      },
    };
  }
}

Home.propTypes = {
  title: PropTypes.string,
  data: PropTypes.array,
};
