import Head from 'next/head';
import { HomePage } from '@/src/components/home/home-page';
import PropTypes from 'prop-types';

export default function Home({ title, data }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </div>
  );
}

export async function getServerSideProps() {
  try {
    const { events_categories } = await import('/data/data.json');
    return {
      props: {
        title: 'Hello everyone!',
        data: events_categories,
      },
    };
  } catch (e) {
    console.error('error occured', e);
    return {
      props: {
        title: 'Hello everyone!',
      },
    };
  }
}

Home.propTypes = {
  title: PropTypes.string,
  data: PropTypes.array,
};